### ISSUE TITLE
Please re-enable automatic tagging of new versions

### ISSUE THREAD

**Issue by besser82** [libyui/libyui-old#108]
At the beginning of the idependent libYui-project new versions were automaticly tagged.  After some period of time this has been faded for some unknown reason.

Please re-enable this, so when the version is bumped in the .changes-file, there should be a new tag on github like `v$major.$minor.$patch`, so I can track and update libyui in Fedora easily.

**Comment by ancorgs** [comment]
We revamped the build system and moved everything to a new unified libyui repositories with (hopefully) proper continuous integration. As far as I know, that includes proper repository tagging. Feel free to open an issue in that new repository if that's not the case.
