### ISSUE TITLE
Not happy with the buildsystem

### ISSUE THREAD

**Issue by dmacvicar** [libyui/libyui-old#16]
After some common stuff shared across the plugins was moved to libyui-devel (which is good), I realized that finding Qt was also there, which is wrong.

We had some internal discussion here at SUSE about the buildsystem.

The problem lays with the design of the buildsystem which goes against all cmake conventions. Instead of having a CMakeLists program that calls helper macros, we have a CMakeLists _data_ which is "magically" computed. But the problem with this approach is that macros are not organized in a certain namespace (LIBYUI_DO_SOMETHING) and what they take as input as output neither. There is no way to control anything that escapes from the "template" (like finding the right ncurses and linking against it) FIND_SOMETHING in CMakeLists does not seem to work before all the INIT_\* stuff, and after it it is too late.

I would like that we move away from this design. The goal is the right one, but the design is not.

Lets follow conventions instead of inventing new ones. With this new system we just invalidated everything we know about cmake in SUSE and can't be productive. With conventions I mean:
- We use FIND_\* from the system
- Do we need a custom FIND_\* : it goes in $CMAKE_PROJECT_DIR/cmake/Modules/FindXXX.cmake
- Do we need a custom macro? : it goes in $CMAKE_PROJECT_DIR/cmake/Modules/XXXMacros.cmake
- Can we share a macro? -devel package installs it into /usr/share/cmake/Modules
  For example, libyui can share FindLibyui.cmake which can then be used in the plugins.
- Macros are named MODULESHARINGIT_WHATDOESITDO ej: LIBYUI_ADD_PLUGIN
- Macros try to use parameters where possible: ej: KDE_ADD_EXECUTABLE wraps ADD_EXECUTABLE, but it takes the name and sources as parameters. No magic grabbing a global variable and generating stuff with it.
- This would transform back the CMakeLists into a flow and not metadata evaluated in INIT_FOO() functions doing magic.

**Comment by ancorgs** [comment]
The build system was fully revamped recently. As a consequence, we even renamed this repository as libyui-old, with the libyui repository now containing a completely reorganized project.

Closing this issue.
