### ISSUE TITLE
The libyui build does not respect the ENABLE_TESTS=OFF cmake option

### ISSUE THREAD

**Issue by GvMariani** [libyui/libyui-old#162]
I'm trying to update the libyui package for the Rosa Fresh 2016.1 distribution, a little Mandriva derivative, on a x86_64 system; ATM the distro has the release 3.3.3 of libyui and I would like to upgrade it to the latest 3.9.3 one.

I'm compiling the sources with gcc 5.5.0 and cmake 3.7.2 and do not want tests nor examples, but only the library and the docs, so I call cmake with the following command line:
`/usr/bin/cmake .. -DCMAKE_INSTALL_PREFIX:PATH=/usr -DCMAKE_INSTALL_LIBDIR:PATH=/usr/lib64 -DINCLUDE_INSTALL_DIR:PATH=/usr/include -DLIB_INSTALL_DIR:PATH=/usr/lib64 -DSYSCONF_INSTALL_DIR:PATH=/etc -DSHARE_INSTALL_PREFIX:PATH=/usr/share -DLIB_SUFFIX=64 -DCMAKE_SKIP_RPATH:BOOL=ON -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DBUILD_SHARED_LIBS:BOOL=ON -DBUILD_STATIC_LIBS:BOOL=OFF '-DCMAKE_MODULE_LINKER_FLAGS= -Wl,--as-needed -Wl,--no-undefined -Wl,-z,now -Wl,-z,relro -Wl,-O1 -Wl,--build-id -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,--unresolved-symbols=ignore-all' -DCMAKE_BUILD_TYPE=RELEASE -DUSE_C_STD=gnu++11 -DYPREFIX=/usr -DDOC_DIR=/usr/share/doc -DLIB_DIR=lib64 -DINSTALL_DOCS=ON -DENABLE_WERROR=OFF -DENABLE_TESTS=OFF -DENABLE_EXAMPLES=OFF -DENABLE_CODE_COVERAGE=OFF`

By looking at the build output, I noticed that the build process, after having finished with the target "yui", tries anyway to process stuff in the directory "tests" (and fails, but this is another issue...):
`[ 97%] Built target yui
/usr/bin/make -f tests/CMakeFiles/FSize_test.dir/build.make tests/CMakeFiles/FSize_test.dir/depend
make[2]: Entering directory '/tmp/abf/rpmbuild/BUILD/libyui-3.9.3/build'
cd /tmp/abf/rpmbuild/BUILD/libyui-3.9.3/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /tmp/abf/rpmbuild/BUILD/libyui-3.9.3 /tmp/abf/rpmbuild/BUILD/libyui-3.9.3/tests /tmp/abf/rpmbuild/BUILD/libyui-3.9.3/build /tmp/abf/rpmbuild/BUILD/libyui-3.9.3/build/tests /tmp/abf/rpmbuild/BUILD/libyui-3.9.3/build/tests/CMakeFiles/FSize_test.dir/DependInfo.cmake --color=
Scanning dependencies of target FSize_test`

That does not seem right, though: if I pass to cmake "ENABLE_TESTS=OFF", I would expect that the test are ignored by the build system... but this is not the case: to actually make the the build ignoring the tests, you have to manually patch PROJECTINFO.cmake and remove "tests" from the SUBDIRS list....

**Comment by shundhammer** [comment]
With the [new CMake build system](https://github.com/libyui/libyui-old/issues/177) this is now no longer an issue: The one test that we have is currently not built or executed, and when we reintroduce that, there will be a `BUILD_TESTS` option. We already have a `BUILD_EXAMPLES` option (default: on) there that you can use.

Please notice that the new unified repository is now https://github.com/libyui/libyui/.
