### ISSUE TITLE
Building of the latest 3.9.3 fails: "error: error: expected constructor, destructor, or type conversion before ';' token"

### ISSUE THREAD

**Issue by GvMariani** [libyui/libyui-old#163]
While trying to build the 3.9.3 sources (gcc 5.5.0 and cmake 3.7.2 on x86_64) I got the failure below while processing the tests (full build log available, if needed):
`[ 97%] Built target yui
/usr/bin/make -f tests/CMakeFiles/FSize_test.dir/build.make tests/CMakeFiles/FSize_test.dir/depend
make[2]: Entering directory '/tmp/abf/rpmbuild/BUILD/libyui-3.9.3/build'
cd /tmp/abf/rpmbuild/BUILD/libyui-3.9.3/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /tmp/abf/rpmbuild/BUILD/libyui-3.9.3 /tmp/abf/rpmbuild/BUILD/libyui-3.9.3/tests /tmp/abf/rpmbuild/BUILD/libyui-3.9.3/build /tmp/abf/rpmbuild/BUILD/libyui-3.9.3/build/tests /tmp/abf/rpmbuild/BUILD/libyui-3.9.3/build/tests/CMakeFiles/FSize_test.dir/DependInfo.cmake --color=
Scanning dependencies of target FSize_test
make[2]: Leaving directory '/tmp/abf/rpmbuild/BUILD/libyui-3.9.3/build'
/usr/bin/make -f tests/CMakeFiles/FSize_test.dir/build.make tests/CMakeFiles/FSize_test.dir/build
make[2]: Entering directory '/tmp/abf/rpmbuild/BUILD/libyui-3.9.3/build'
[ 98%] Building CXX object tests/CMakeFiles/FSize_test.dir/FSize_test.cc.o
cd /tmp/abf/rpmbuild/BUILD/libyui-3.9.3/build/tests && /usr/share/colorgcc/c++   -DBOOST_TEST_DYN_LINK -DTESTS_SRC_DIR=\"/tmp/abf/rpmbuild/BUILD/libyui-3.9.3/tests\" -DVERSION=\"3.9.3\" -I/tmp/abf/rpmbuild/BUILD/libyui-3.9.3/tests/../src  -O2 -Wa,--compress-debug-sections -gdwarf-4 -fvar-tracking-assignments -frecord-gcc-switches -Wstrict-aliasing=2 -pipe -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -ffat-lto-objects -fno-delete-null-pointer-checks -fstack-protector --param=ssp-buffer-size=4 -fPIC -std=c++0x -fmessage-length=0 -Wall -O3   -o CMakeFiles/FSize_test.dir/FSize_test.cc.o -c /tmp/abf/rpmbuild/BUILD/libyui-3.9.3/tests/FSize_test.cc
/tmp/abf/rpmbuild/BUILD/libyui-3.9.3/tests/FSize_test.cc:40:41: error: expected constructor, destructor, or type conversion before ';' token
 BOOST_TEST_GLOBAL_FIXTURE( LogWarnings );
                                         ^
make[2]: *** [tests/CMakeFiles/FSize_test.dir/build.make:66: tests/CMakeFiles/FSize_test.dir/FSize_test.cc.o] Error 1
make[2]: Leaving directory '/tmp/abf/rpmbuild/BUILD/libyui-3.9.3/build'
make[1]: *** [CMakeFiles/Makefile2:290: tests/CMakeFiles/FSize_test.dir/all] Error 2
make[1]: Leaving directory '/tmp/abf/rpmbuild/BUILD/libyui-3.9.3/build'
make: *** [Makefile:153: all] Error 2`

This happens even when passing ENABLE_TESTS=OFF to cmake (see issue #162); this is the cmake command line I'm using:
`/usr/bin/cmake .. -DCMAKE_INSTALL_PREFIX:PATH=/usr -DCMAKE_INSTALL_LIBDIR:PATH=/usr/lib64 -DINCLUDE_INSTALL_DIR:PATH=/usr/include -DLIB_INSTALL_DIR:PATH=/usr/lib64 -DSYSCONF_INSTALL_DIR:PATH=/etc -DSHARE_INSTALL_PREFIX:PATH=/usr/share -DLIB_SUFFIX=64 -DCMAKE_SKIP_RPATH:BOOL=ON -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DBUILD_SHARED_LIBS:BOOL=ON -DBUILD_STATIC_LIBS:BOOL=OFF '-DCMAKE_MODULE_LINKER_FLAGS= -Wl,--as-needed -Wl,--no-undefined -Wl,-z,now -Wl,-z,relro -Wl,-O1 -Wl,--build-id -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,--unresolved-symbols=ignore-all' -DCMAKE_BUILD_TYPE=RELEASE -DUSE_C_STD=gnu++11 -DYPREFIX=/usr -DDOC_DIR=/usr/share/doc -DLIB_DIR=lib64 -DINSTALL_DOCS=ON -DENABLE_WERROR=OFF -DENABLE_TESTS=OFF -DENABLE_EXAMPLES=OFF -DENABLE_CODE_COVERAGE=OFF`
No errors or warnings before the failure spot...
I tested all the releases > 3.3.3 (the one provided by my distro) and all show the same build error...

**Comment by shundhammer** [comment]
This should not happen anymore now with the new CMake build system. Please notice that the new unified repository is now https://github.com/libyui/libyui/.
