### ISSUE TITLE
Consolidating libyui Packaging and Build Environment

### ISSUE THREAD

**Issue by shundhammer** [libyui/libyui-old#177]
## Problem

The libyui project is split up into many parts which each have their own source code repository and each produce their own binary package (RPM in the case of SUSE packages).

That makes adding new features painful for us developers because we need to maintain source code (API) and binary (ABI) compatibility:

- We need to bump the library SO number in all related packages at the same time to maintain that ABI compatibility.

- Package dependencies (RPM `Requires` and `BuildRequires`) need to be adapted in many different places.

- We need to create many pull requests that each need to be peer-reviewed (according to our own established rules). That is a lot of work for the developer making the change as well as for the reviewers.

- Such a change cannot be done in an atomic way. This invariably leads to a chaotic transitional phase where some packages are already checked into openSUSE Factory and others are not; some may have failed building in any of the various stages of CI and OBS. During that phase, we are flooded with errors from OBS and our QA people, causing additional workload for them and for us. It takes a while for that to settle down.

- We try to minimize that transitional phase, but it's hard. It's a lot of work to create all those separate pull requests. It's error-prone. It takes a while until they are all reviewed. It's hard to keep an overview about open and pending ones. We need to wait until the last one is reviewed and then quickly merge them all to minimize the disruption.

- During the transitional phase, our own CI doesn't work; it's a chicken-egg problem: The docker image for building UI packages will contain outdated lower-level UI libs, so dependent UI packages will fail to build.

  _Example: We add a new YMogrify widget. It will go to libyui first, then libyui-qt, libyui-ncurses, the UI bindings (yast-ycp-ui-bindings). But the libyui-docker image still contains the old libyui without YMogrify, so building the Qt UI with a new YQMogrify widget that inherits YMogrify will fail (same with the NCurses version). It's not always possible to maintain binary compatibility to have an additional cycle with the new libyui containing the changes going to the docker image first (and it takes a considerable while)._

## Requirements

- We want a generic libyui that is independent of any specific toolkit like Qt, Gtk, NCurses or any YaST libs.

- Specific UIs like the Qt, NCurses, Gtk UIs (libyui-qt, libyui-ncurses, libyui-gtk) are plug-ins that are loaded on demand. A user can choose to install only one of them or several ones.

- Some of the specific UIs have additional optional components.

  For YaST, we have a package management plug-in for Qt and for NCurses each, libyui-qt-pkg and libyui-ncurses-pkg. For our QA teams we collaborated with them to provide REST API plug-ins for advanced communication between openQA and the UI (sending the IDs of widgets to activate instead of keystrokes, introspection of internal widget states by openQA).

- It must be possible to build libyui and some or all of the specific UIs without needing any YaST libs or packages.

- It must be possible to develop and maintain separate specific UIs or plug-ins independently of any YaST infrastructure and in separate Git / GitHub (or whatever a developer chooses) repositories.

- It must be possible to build libyui without Qt or Gtk (possibly with a special build parameter or a special pre-build script).

- API (source code) compatibility: libyui should have a stable API that should be backwards compatible as much as possible so existing software built against it does not need to be changed because features are added to libyui.

- ABI (binary) compatibility: A libyui with the same library SO number (libyui14) is required to be 100% binary compatible so an application linked against that libyui14 does not crash because of bug fixes in an updated libyui binary package. We need to be able to ship fixed libyui binary packages with the same SO number without having to recompile any application linked against libyui.

- We need package dependencies that ensure API and ABI compatibility. That means when a libyui with a new SO number is released, the dependency resolver (libzypp / zypper / yast2 sw_single) automatically also upgrades packages built against libyui to the newer versions using the newer libyui.

### Merging libyui-qt* and libyui-ncurses* back into the libyui Repo

Basic Idea: Merge the GitHub repos of libyui-qt* and all libyui-ncurses* back into one unified libyui repo; but still create several separate binary packages (RPMs) from that repo so a user can choose to install or not install some of them (with/without Qt, with/without package plugin).

libyui-gtk and other community-maintained parts would still remain separate to avoid access restrictions for them.

_See below for more details._

## Result

- New CMake build environment which works stand-alone and also when all libyui repos are consolidated into one: https://github.com/libyui/libyui/pull/178 and sub-PRs

- @mvidner's work on consolidating the libyui repos into a single big one (_insert link here_)

## Why Discuss This Here?

Because it's a public place for all the world to read and to contribute to the discussion, and it's recorded for the future.

Unlike Bugzilla, the GitHub issue tracker allows editing, and images can easily be added.

## How to Migrate a Libyui Plug-in Package to the new Build Environment

The SUSE-maintained libyui plug-ins are already migrated; see PR https://github.com/libyui/libyui/pull/178 and the PRs mentioned there.

For community-maintained libyui plug-ins, see the migration PR of the Qt UI for instructions and as an example: https://github.com/libyui/libyui-qt/pull/143

**Comment by shundhammer** [comment]
@anaselli : You might be interested in this.

**Comment by shundhammer** [comment]
## Idea: Merging libyui-qt* and libyui-ncurses* back into the libyui Repo

General idea:

- Move all Qt and NCurses UI packages back into the libyui repo
- Have one toplevel Makefile / CMakefile to build them all in sequence
- Have one common .spec file to generate the binary packages as needed
- Have one or more _bootstrap_ scripts to include or exclude subpackages as needed from building so it's still possible to build without Qt or even without the NCurses UI

- Keep repos / packages that are community-maintained as they are (libyui-gtk and friends)

To be discussed:

- Also put the SWIG bindings (libyui-bindings) there? 
- Also put the yast-ycp-ui-bindings there? (How much of a problem would that be?)

Additional benefits:

- We could easily move the new libyui-ncurses / libyui unit tests there, and they would automatically be executed

**Comment by rwx788** [comment]
Managing everything as single product sounds like a good idea to me, so that we manage builds from the single place, as anyway mentioned components are tightly coupled. We could use git modules to still keep source code in separate repos, but increasing SO version, etc. would not need multiple PRs which also have to be merged in the right order.

**Comment by shundhammer** [comment]
I used Git submodules in the past, and I was very unhappy about them; they tend to add a whole new level of complexity.

While they do have their place when you have to handle external libs in a project that might need updating from upstream every once in a while, I believe in our case they would not contribute any benefit that might outweigh the handling issues.

Also, I am not sure if a PR can really stretch among submodules; we might still be stuck with the current dozen (or so) of PRs for each change that requires a SO bump.

**Comment by shundhammer** [comment]
## Idea: Auto-generate change logs from commit messages?

We are already doing that in _linuxrc_ and in _libstorage_. That removes a serious bottleneck: As the repo grows, it is becoming more likely that several people are working on different parts in parallel, and the _.changes_ file gets merge conflicts because everybody is adding entries in the first few lines.

A generated change log completely avoids that. @wfeldt has some scripts to make that possible. I am not sure, but I think even the version bump is automated (because _VERSION.cmake_ and _.spec_ files also become a magnet for merge conflicts).

**Comment by mvidner** [comment]
## Means of Combining Repos

Submodules (or subtrees) would not solve our problems. We do need a plain single repo. The recommended way is to simply `git merge ...` the histories. Of course we will want to move some repos to a subdirectory. That can be done

1. either *before* the merge, by rewriting history (`git filter-repo` or `git filter-branch`) of libyui-foo to give all commits a plugin-foo parent dir,
2. or *after* the merge, by `git mv src/YQ* plugin-qt/src`

I think we will have to try both to see which works better with subsequent code archaeology.

Source: https://stackoverflow.com/questions/1425892/how-do-you-merge-two-git-repositories

**Comment by mvidner** [comment]
> Auto-Generate Change Logs from Commit Messages?

I have reservations about this even in the repos where it's currently used, but for libyui I see a bigger problem: we are going to produce several binary RPMs, and I would dislike them all having the same unified changelog.

For solving the `*.changes` conflicts, I use https://github.com/mvidner/changelog-chew

**Comment by anaselli** [comment]
> Auto-Generate Change Logs from Commit  Messages?

Well even if that helps a lot, i think it's hard to link single commits with high level functions as you could find in a changelog.
But yes i used it in svn adding some tags though, e.g. label that parsed would remove the line as output (iirc was [sv2cl](https://linux.die.net/man/1/svn2cl)). 
Anyway a commit message how to should be provided, not all the commits have meanings...

**Comment by wfeldt** [comment]
> Auto-Generate Change Logs from Commit Messages?

There's no arguing around the fact that things like version numbers or dates don't logically belong into commits that are intended to be reused in other branches. It's just causing troubles and having a script to solve a problem that shouldn't be there in the first place is not really optimal.

Commit messages are as good or bad as you write them. And stacking 'fix typo' or 'minor correction' should obviously be avoided. You have every freedom to structure a pr into meaningful bits. Other projects are way more strict than what we do here.

Also, the tooling that exsists does give you the freedom to not put every commit message into the changelog. It's just that this is barely needed.

It's a long standing discussion in the yast team. My (practical) view here is that the factual quality of our hand-written changelog doesn't quite justify the effort. ;-)

**Comment by shundhammer** [comment]
@anaselli:

There would be more messages in such a change log, no doubt. For each pull request, one of them (but no more) would need to include a bug or feature number  ("(bsc#471122)").

I have been doing that for quite a while already; it proved to work well (IMHO) in both the _linuxrc_ and the _libstorage-ng_ repos.

Of course other commits will appear here as well; if you followed recent changes in libyui-ncurses, you might have seen quite a number of intermediate commits titled something like "coding style", "class reorganization" etc.

Does that hurt a user? I don't think so. To the contrary: It records for the general public that and how we are constantly improving and refactoring our software. If you compare with the change logs of most other packages, you will find that they in 99.8% of all cases only get nondescript messages like "updated to 3.17.23" that does not give away any useful information what was changed.

And besides, any migration towards a generated change log would not affect community-maintained packages like libyui-gtk at all, of course.

**Comment by anaselli** [comment]
> Does that hurt a user? I don't think so. To the contrary: It records for the general public that and how we are constantly improving and refactoring our software. If you compare with the change logs of most other packages, you will find that they in 99.8% of all cases only get nondescript messages like "updated to 3.17.23" that does not give away any useful information what was changed.

Didn't mean that :) Just think that a long changelog is probably not read by most, especially if that contains a large number of "typo", "minor fixing", "error string" or anything like that, those are difficult to read in history too, but differences help to understand them though...

While a good one that tells only differences from release to release could be helpful and probably to be read more... just my opinion of course

> And besides, any migration towards a generated change log would not affect community-maintained packages like libyui-gtk at all, of course.

I don't agree, why we should have such a difference? even when i wrote mga plugins i tried to use the same policy for changelog, cmake and so on and so for... Honestly i don't like either a community maintained concept, i'd really like to see a community involvement in all the project instead... I see you don't mean to maintain libyui-gtk, but that doesn't mean that if @anaselli disappears all vanish...

**Comment by jreidinger** [comment]
I agree that we should not make difference who maintain given plugin and have same rules unless there is a strong oposition. Same I think that if we consolidate plugins under one git repo, then it makes sense to have there also all backends, including gtk ones and only difference should be that in spec file for SUSE it won't create gtk rpms and just skip that part. We should not make anything second class citizens.

**Comment by mvidner** [comment]
I have made a prototype of a monorepo: https://github.com/mvidner/libyui-combined-alpha-1

The script used for that, [slurp][], is in https://github.com/mvidner/libyui-combined-scripts

[slurp]: https://github.com/mvidner/libyui-combined-scripts/commit/55ffd390819cfd39866ba5642a1d1bffa88fc966

**Comment by anaselli** [comment]
Does that mean with suse no one can have libyui gtk, neither in not core repository? Sad to hear that

**Comment by jreidinger** [comment]
@anaselli by SUSE I mean SUSE Linux Enterprise (SLE in short) which contain only software for which provide SUSE as company support. It does not mean openSUSE and its distros or any package provided via package hub, which is not supported by SUSE, but just on best effort by some partners.

**Comment by shundhammer** [comment]
> I agree that we should not make difference who maintain given plugin and have same rules unless there is a strong oposition. 

There is.

> Same I think that if we consolidate plugins under one git repo, then it makes sense to have there also all backends, including gtk ones and only difference should be that in spec file for SUSE it won't create gtk rpms and just skip that part. We should not make anything second class citizens.

No.

While we _could_ also drag libyui-gtk into that plugins/ subdirectory, who knows what other ones somebody from the outside would come up with? We don't want to give everbody commit permissions to that new libyui repo, and we don't want to restrict the community to add whatever they like to existing community-maintained plugins as well as adding any new ones.

We have a responsibility for the libyui core and for the plugins we maintain (-qt, -qt-pkg, -qt-graph, -qt-rest-api, -ncurses, -ncurses-pkg, ncurses-rest-api) at the very minimum for the SLE products that our commercial customers pay for support. So we need restrictive access to that to make sure we can actually support them properly.

For community-maintained parts, there is no necessity to be that restrictive, so we should not impose artificial restrictions to our community. That alone is reason to keep that apart.

**Comment by shundhammer** [comment]
> Does that mean with suse no one can have libyui gtk, neither in not core repository? Sad to hear that.

No, definitely not.

I am strictly against restricting access to the source code repo of libyui-gtk or any other (future?) community-maintained libyui plugins.

At the same time, it must of course be possible to use any of them with SUSE Linux, both openSUSE and SLE. While we, the YaST team, are not in a position to provide any support for that, in the past community support worked quite well IMHO.

**Comment by shundhammer** [comment]
## To Do

- Write a document clarifying the status of libyui-gtk with regard to community-maintained vs. maintained by the YaST team.

- Write a document clarifying how to build all the UI parts in the new libyui directory with and without certain parts such as libyui-qt* (requiring Qt), libyui-*pkg (requiring libzypp), libyui*rest-api.

- Add some bootstrap scripts to the toplevel project directory to make it easy to build all parts, just a bare-bone libyui without any additional parts, and a reasonable minimalistic selection of them (libyui, libyui-ncurses, libyui-bindings).

- Make sure to have subdirectories for individual parts self-sufficient enough to do an isolated build there (only libyui-ncurses, only libyui-bindings).

**Comment by shundhammer** [comment]
Separate document about the CMake environment in our libyui* packages:
https://gist.github.com/shundhammer/d96a63a1cab8245d20c2e3556238a114

**Comment by shundhammer** [comment]
First step: New CMake-based build environment for all SUSE-maintained libyui* repos / packages.

Master PR: https://github.com/libyui/libyui/pull/178

The individual repos and packages are still separate. The new build environment integrates seamlessly with the old one, i.e. it is perfectly possible to use repos / packages with the new one in parallel with the old one.

The old buildtools are still installed as they were, so they remain available for repos / packages with the old build environment.

The new build environment now takes sibling libyui* repos into account and prefers include files from there; i.e. libyui-qt/src/*.cc will now include headers from ../libyui/src, so make sure to update the checked-out clones when building (or not have them there in the first place; remove or move to another subdirectory). The basic idea is to enable transactional changes, and of course to prepare from merging the core libyui repos / packages to a common large repo.

**Comment by shundhammer** [comment]
The new repository where this is implemented is https://github.com/libyui/libyui/.
