### ISSUE TITLE
libyui should have a logo

### ISSUE THREAD

**Issue by mlandres** [libyui/libyui-old#24]
The libyui org here on github needs an avatar and for use in the web as well.

**Comment by hellcp** [comment]
Something like this?
![libyui](https://user-images.githubusercontent.com/30577011/47265383-497ffa00-d4f5-11e8-9cbc-c64b58a29528.png)
[SVG](https://gist.github.com/hellcp/369bee3996f21975178a9ae0bbc301a3)
cc by-sa 4.0

**Comment by ancorgs** [comment]
@shundhammer, @mvidner, @joseivanlopez  Any clear adoption plan? If not, I will close the issue.

**Comment by shundhammer** [comment]
A logo would probably give it a more personal touch, and @hellcp 's draft looks nice; but what exactly would we do with it? Where would it come into play?
