### ISSUE TITLE
Link to documentation is outdated

### ISSUE THREAD

**Issue by neuschaefer** [libyui/libyui-old#78]
Hi.
The link to the documentation (http://doc.opensuse.org/projects/libyui) seems to be wrong, it only shows a directory listing. The following link shows documentation, but it looks a bit outdated (it has apparently last been updated in mid-2011):
http://doc.opensuse.org/projects/libyui/HEAD/

**Comment by ancorgs** [comment]
That link is not present in the README anymore. So we could consider this issue as not longer valid.
